# -*- coding: utf-8 -*-
"""2201  LeetCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFu3m1MaDxRWhYtT-bJRBTvEZ2B5AOGA
"""

#IMC

class Solution:
    def digArtifacts(self, n: int, artifacts: list[list[int]], dig: list[list[int]]) -> int:
        uncovered = [[False] * n for _ in range(n)]
        for digged in dig:
            uncovered[digged[0]][digged[1]] = True

        count = 0
        for artifact in artifacts:
            flag = True
            for i in range(artifact[0], artifact[2] + 1):
                for j in range(artifact[1], artifact[3] + 1):
                    if not uncovered[i][j]:
                        flag = False
                        break
                if not flag:
                    break
            if flag:
                count += 1
        return count