# -*- coding: utf-8 -*-
"""LeetCode_371.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YpKijSgZgPpQcdZL_HNip_y7a3AxENro
"""

def getSum(a: int, b: int) -> int:
    mask = 0xFFFFFFFF

    max_int = 0x7FFFFFFF

    while b != 0:
        carry = (a & b) << 1
        a = (a ^ b) & mask
        b = carry & mask

    return a if a <= max_int else ~(a ^ mask)

# Example usage
# result = getSum(1, 2)
# print("Sum:", result)  # Output: 3